export const prompts: string[] = [
  'apple kiwi watermelon pineapple grape',
  'pear grape melon',
  'banana kiwi',
  'kiwi pineapple orange watermelon',
  'mango pear',
  'pear pineapple kiwi',
  'grape',
  'pineapple watermelon kiwi grape',
  'banana pear kiwi',
  'pineapple watermelon melon',
  'kiwi orange',
  'pear watermelon mango',
  'apple orange',
  'pear grape kiwi',
  'watermelon pineapple orange melon',
  'watermelon kiwi',
  'grape melon',
  'banana watermelon',
  'kiwi watermelon grape',
  'orange pineapple'
];

export const keywords: string[] = [
  'tunnel',
  'cabinet',
  'frost',
  'dollar',
  'photograph',
  'pilot',
  'guitar',
  'harvest',
  'mansion',
  'sunset',
  'fountain',
  'diamond',
  'saddle',
  'basket',
  'cactus',
  'butterfly',
  'compass',
  'staircase',
  'thunder',
  'candle'
];
